name: Backend Build and Push

on:
  push:
    branches:
      - dev
    paths:
      - 'src/backend/**'
      - '.github/workflows/backend-build-and-push.dev.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      branch_name: ${{ env.BRANCH_NAME }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get branch name
      id: branch-name
      run: |
        if [[ $GITHUB_BASE_REF ]]; then
          echo "BRANCH_NAME=$GITHUB_BASE_REF" >> $GITHUB_ENV
        else
          echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
        fi

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: us-east-1
        role-session-name: GitHubActionsECRPushSession

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ env.BRANCH_NAME }}-backend-repo
        IMAGE_TAG: ${{ env.BRANCH_NAME }}-${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./src/backend
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Tag image as latest for dev branch
      if: env.BRANCH_NAME == 'dev' && github.event_name == 'push'
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ env.BRANCH_NAME }}-backend-repo
        IMAGE_TAG: ${{ env.BRANCH_NAME }}-${{ github.sha }}
      run: |
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      BRANCH_NAME: ${{ needs.build-and-push.outputs.branch_name }}

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: us-east-1
        role-session-name: GitHubActionsECRPushSession

    - name: Download migration task definition
      run: aws ecs describe-task-definition --task-definition ${{ env.BRANCH_NAME }}-backend --query taskDefinition > task-definition.json

    - name: Update task definition with new image
      if: env.BRANCH_NAME == 'dev' && github.event_name == 'push'
      id: download-taskdef
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: 'task-definition.json'
        container-name: backend
        image: ${{ steps.login-ecr.outputs.registry }}/${{ env.BRANCH_NAME }}-backend-repo:${{ env.BRANCH_NAME }}-${{ github.sha }}

    - name: Deploy to ECS
      if: env.BRANCH_NAME == 'dev' && github.event_name == 'push'
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.download-taskdef.outputs.task-definition }}
        service: ${{ env.BRANCH_NAME }}-backend
        cluster: ${{ env.BRANCH_NAME }}-cluster
        wait-for-service-stability: true